package errs

const (
	InvalidAgentToken             = UnauthenticatedError("invalid agent token")
	InvalidAgentID                = InvalidArgumentError("invalid agent ID")
	InvalidAgentName              = InvalidArgumentError("invalid agent name")
	InvalidMachineID              = InvalidArgumentError("invalid machine ID")
	InvalidAgentType              = InvalidArgumentError("invalid agent type")
	InvalidAgentVersion           = InvalidArgumentError("invalid agent version")
	UnsupportedAgentVersion       = InvalidArgumentError("unsupported agent version")
	InvalidAgentEdition           = InvalidArgumentError("invalid agent edition")
	InvalidAgentOperatingSystem   = InvalidArgumentError("invalid agent operating system")
	InvalidAgentArchitecture      = InvalidArgumentError("invalid agent architecture")
	InvalidAgentFlags             = InvalidArgumentError("invalid agent flags")
	InvalidAgentFlag              = InvalidArgumentError("invalid agent flag")
	InvalidAgentRawConfig         = InvalidArgumentError("invalid agent raw config")
	InvalidAgentMetadata          = InvalidArgumentError("invalid agent metadata")
	UpdateAgentVersionForbidden   = PermissionDeniedError("update agent version forbidden")
	UpdateAgentEditionForbidden   = PermissionDeniedError("update agent edition forbidden")
	UpdateAgentFlagsForbidden     = PermissionDeniedError("update agent flags forbidden")
	UpdateAgentRawConfigForbidden = PermissionDeniedError("update agent raw config forbidden")
	UpdateAgentMetadataForbidden  = PermissionDeniedError("update agent metadata forbidden")
	AgentGone                     = GoneError("agent gone")
	MachineIDConflict             = ConflictError("machine ID conflict")
	AgentNotFound                 = NotFoundError("agent not found")
	AgentsQuotaExceeded           = PermissionDeniedError("agents quota exceeded")
	InvalidTag                    = InvalidArgumentError("invalid tag")
)
